STANDALONE:
	gcc -g -std=c99  main.c mouse.c -L /usr/lib/arm-linux-gnueabihf/ -levdev -I /usr/include/libevdev-1.0/

LIBRARY:
	gcc -g -std=c99 -c mouse.c -L /usr/lib/arm-linux-gnueabihf/ -levdev -I /usr/include/libevdev-1.0/
