STANDALONE:
	gcc main.c mouse.c -L /usr/lib/arm-linux-gnueabihf/ -levdev -I /usr/include/libevdev-1.0/

LIBRARY:
	gcc -c mouse.c -L /usr/lib/arm-linux-gnueabihf/ -levdev -I /usr/include/libevdev-1.0/
